### ISSUE TITLE
Záznamy bez souboru

### ISSUE THREAD

**Issue by kosarko** [ufal/ukrepo#22]
Chceme povolit metadata only záznamy?

**Comment by mjtecka** [comment]
Zatím ne, teď to nepovažujeme za katalog. Uvidíme, jaký bude vývoj kolem národního katalogu (myslím Národní metadatový adresář/NMA z NRP).

((Nicméně předpokládám, že u rozpracovaných, nezveřejněných záznamů je existence záznamů bez přidaných souborů možná))

**Comment by kosarko** [comment]
jj. rozpracovany zaznamy lze ukladat bez souboru. Defaultne se soubory vyzadujou. Pokud by to bylo potreba zmenit ta konfiguracni property se jmenuje `webui.submit.upload.required`
